version = 1

test_patterns = [
    "test/**",
    "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["dev-requirements.txt", "emscripten-requirements.txt", "mypy-requirements.txt"]

    [analyzers.meta]
    runtime_version = "3.x.x"
